version: '3.3'

services:

  server:
    container_name: server
    image: nanoninja/php-fpm
    depends_on:
      - database
    ports:
      - 8000:8000
    volumes:
      - ./:/var/www/html/
    command: "php artisan serve --host=0.0.0.0 --port=8000"

  database:
    container_name: database
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    hostname: database
    restart: always
    volumes:
      - ./filesystem/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      TZ: "America/Argentina/Buenos_Aires"
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
